### ISSUE TITLE
Sponsor id name 

### ISSUE THREAD

**Issue by anujjhawar28** [mayank30/fdchain#11]
when in LOGIN pannel 

when in new registration ....

when someone add someone or his referral sponsor id then we can give one more thing there

NAME of the owner of sponsor id ...
so that it can prove new user that yes it is there ,,...... and gives mirror and positive mind set

**Comment by anujjhawar28** [comment]
I would like to discuss more on this .. 
like how and where 

If u can add link here or screenshot will be better and fast for me to understand ..

**Comment by mayank30** [comment]
We will not show sponser id  / mobile number to end user .. that it we will not shoot name of person whom it belongs to ..
