### ISSUE TITLE
issues

### ISSUE THREAD

**Issue by anujjhawar28** [mayank30/fdchain#15]

**Comment by anujjhawar28** [comment]
1.New Password Should not be same with old password.
2.Password should mix of Upper Lower case, Number, Special Character.
3.Don't share your password, even to fdpay customer support.
4.In case if lost your account access please let us know or directly do forgot password, we will shoot email with new password.

---
1. iske hisssaab se agar koi same password daalta (new,old,repeat me) he  to use aana chahaiye na ki "password is same Enter different"
   isme abhi password changed successfully likha aara he  !!

**Comment by mayank30** [comment]
fixed
