### ISSUE TITLE
sponsor search

### ISSUE THREAD

**Issue by anujjhawar28** [mayank30/fdchain#22]
aap pure netwrok ka NETWORK PANNEL me hi kisi bhi bande ka sponsor id daalke uski details search kar sakte he ................
aur jo new user ki apn log upline dikha rahe he na wo har member jo network me he sabka upline ki sponsor id denge okkkk...........
## it will be more helpful............

aur sponsor search karega to apn uss is ka name email contact and status and baaki tu dekh lena aur kya de sakte he.......

**Comment by mayank30** [comment]
Done 

added in my networks
